### ISSUE TITLE
Correct response for a DECRQSS query?

### ISSUE THREAD

**Issue by j4james** [hackerb9/vt340test#13]
According to the VT330/VT340 Text Programming Reference, the response to the `DECRQSS` query is a `DECRPSS` sequence with a parameter value indicating whether the request was valid or not.

> 0 = host's request is valid.
> 1 = host's request is invalid.

I've checked as many other manuals as I could find, and most seem to agree with this. This includes the VT320 user manual, the VT420 programming reference, the VT510 programming reference, and the VT520/VT525 programming reference.

However, the DEC STD-070 reference describes these values the other way, and so do the VT382 manuals.

> 0 = unknown selection or setting
> 1 = request successful

I'm hoping you'll be able to confirm which of these is correct, at least for the VT340.

Here is an example of a valid query (requesting the SGR state):

```
printf '\eP$qm\e\\'; read -n 100
```

In theory it should respond with something like this:

```
^[P0$r0m^[\
```

And this is an example of an invalid query:

```
printf '\eP$qx\e\\'; read -n 100
```

Which should respond with something like this:

```
^[P1$r^[\
```

If that's not what you're seeing, then maybe we've got another entry for the errata doc.

**Comment by hackerb9** [comment]
The VT320 manual and DEC STD-070 seem to be correct while the VT340 manual is mistaken.  This make some sense since the VT320 came after the VT330 & 340. 

```
$ printf '\eP$qm\e\\'; read -rd '\'; echo
^[P1$r0m^[\

$ printf '\eP$qx\e\\'; read -rd '\'; echo
^[P0$r^[\
$
```

**Comment by j4james** [comment]
Thanks. That's a relief, actually, because that's what most modern terminals have been doing. But note that the test you added to the errata doc has the wrong read delimiter (it's using a forward slash rather than backslash).

**Comment by hackerb9** [comment]
Thanks for catching that. Wouldn't want someone else to have to create an errata doc for my errata doc.

**Comment by dnkl** [comment]
Just wanted to say thanks!

I was basing my own implementation on the VT510 manual, and was confused by both XTerm's and mlterm's responses...

**Comment by craigbarnes** [comment]
This came up recently in the foot IRC channel, which led me to read [something] in xterm's documentation I'd never noticed before:

> Sometimes the manuals are simply incorrect. For example, testing a
> DEC VT420 in 1996 showed that the documented code for a valid or
> invalid response to DECRQSS was reversed.
>
> The VT420 test results were incorporated into the vttest program.
> At the time, DEC STD 070 was not available, but it also agrees with
> vttest. Later, documentation for the DEC VT525 was shown to have
> the same flaw.

Just thought I'd mention it here for posterity/completeness.

[something]: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Technical-manuals:~:text=testing%20a%0A%20%20%20%20DEC%20VT420%20in%201996%20showed%20that%20the%20documented%20code%20for%20a%20valid%20or%0A%20%20%20%20invalid%20response%20to%20DECRQSS%20was%20reversed
