### ISSUE TITLE
Extended Cursor Position Report (DECXCPR)

### ISSUE THREAD

**Issue by j4james** [hackerb9/vt340test#23]
I've just realised that this might be another candidate for your errata doc, or if it's not an error, it would be good to know.

According to the VT330/VT340 Text Programming Reference (page 202), the response to the _Extended Cursor Position Report_ should look like this:

```
CSI Pl ; Pc ; Pp R 
```

The VT420, the VT510, and the VT520/VT525 programmer references all say the same thing. However, the DEC STD-070 reference documents it as:

```
CSI ? Pl ; Pc ; Pp R 
```

Most terminal emulators seem to have followed the DEC STD-070 documentation (i.e. including the `?` private parameter specifier), so I always assumed the other documentation was incorrect, but it would be good to have that confirmed.

**Comment by j4james** [comment]
@hackerb9 Did you ever get a chance to look at this? A simple test case:

```
printf '\e[?6n'; read -d 'R'
```

**Comment by hackerb9** [comment]
Sorry, been under a mountain. Will try to excavate the VT340 and let you know today.

**Comment by hackerb9** [comment]
Thanks for telling me about that. As you expected,

`read -p $'\e[?6n' -d R -t 1`

returns

<kbd>Esc</kbd><kbd>[</kbd><kbd>**?**</kbd><kbd>2</kbd><kbd>4</kbd><kbd>;</kbd><kbd>1</kbd><kbd>;</kbd><kbd>1</kbd><kbd>R</kbd>

I'm not surprised the tech writers got confused between the ANSI standard (sans question mark) and DEC Private (with question mark) versions. I don't think any of the other Device Status Reports have both ANSI and DEC versions. 

I'll add it to the Errata that the text programmer's manual (and pocket programmer's guide, page 43) should have said:

#### DSR &mdash; Extended Cursor Position Report (DECXCPR)
The host asks the terminal for the current cursor position, including the current page number.

Exchange | Sequence | Meaning
-|-|-
Request<br/>(Host to VT300) | <kbd>CSI</kbd><kbd>?</kbd><kbd>6</kbd><kbd>n</kbd> | The host asks for an extended<br/>cursor position report<br/>(DECXCPR).
DECXCPR response<br/>(VT300 to host) | <span><kbd>CSI</kbd><kbd>?</kbd>**Pl**<kbd>;</kbd>**Pc**<kbd>;</kbd>**Pp**<kbd>R</kbd></span> | The terminal indicates that<br/>the cursor is currently at<br/>line **Pl**, column **Pc**, on page **Pp**.

**Comment by j4james** [comment]
That's good to know. Thanks for confirming that.
