### ISSUE TITLE
Multiple DSR requests at the same time

### ISSUE THREAD

**Issue by j4james** [hackerb9/vt340test#32]
This is something I recently discovered on the VT240, and I'm curious to see if it's supported on the VT340 as well. If you pass multiple parameters to a `DSR` query, it's treated the same as if you'd submitted multiple queries. For example `\e[5;6n` queries both the operating status and the cursor position.

On the VT240, there is a limit of two `DSR` queries at the same time, but that appears to be a general limit on queries, rather than a limit on the number parameters that `DSR` allows. For example, if you output something like `\e[5n\e[6n\e[?15n`, it only responds to the first two queries, so I'm guessing this is some sort of buffer constraint.

I've created a little test script for this, which first goes through all the individual `DSR` queries supported by the VT340, and then tries combining them to see if that is supported. It allows a couple of seconds for each response, so you can expect it to take at least 12 seconds to finish.

https://gist.github.com/j4james/de4b62cf884785dfb15182190d4e907b

I wouldn't be surprised if the VT340 only supports a single parameter, though - that's almost certainly the case for later models. At level 4 they introduced a `DSR` checksum query for the text macro extension, and the second parameter of that query is an ID. So `\e[?63;6n` is a macro checksum query with an ID of 6, rather than a macro checksum combined with `DSR-XCPR`.

**Comment by hackerb9** [comment]
Looks like the VT340 only allows one query per **DSR**. Results are [here](https://github.com/hackerb9/vt340test/blob/main/j4james/dsr_multiple.output).

**Comment by j4james** [comment]
Thank you! It's good to know it is does at least respond to the full list of queries when separated. The two query limit on the VT240 is a bit annoying.

You can close this issue now if you want. There's nothing further I wanted to ask.
